ci: run tests in matrix also for macOS and Windows

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,7 +13,11 @@ concurrency:
 
 jobs:
   main:
-    runs-on: ubuntu-latest
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest, macos-latest, windows-latest]
+      fail-fast: false
     env:
       TEST_RESOURCES: test-resources
     steps:
@@ -32,19 +36,44 @@ jobs:
       - name: npm-compile
         run: npm run compile
 
-      - name: UI test
-        run: xvfb-run --auto-servernum npm run ui-test
+      - name: UI test (macOS, windows)
+        if: matrix.os != 'ubuntu-latest'
+        run: npm run ui-test
 
-      - name: Store UI test log
+      - name: UI test (linux)
+        if: matrix.os == 'ubuntu-latest'
+        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npm run ui-test
+
+      - name: Store UI test logs
         uses: actions/upload-artifact@v4
         if: failure() || cancelled()
         with:
-          name: uitest-logs
+          name: logs-${{ matrix.os }}
           path: test-resources/settings/logs/*
 
       - name: Store UI Test screenshots
         uses: actions/upload-artifact@v4
         if: failure() || cancelled()
         with:
-          name: uitest-screenshots
+          name: screenshots-${{ matrix.os }}
           path: test-resources/screenshots/*.png
+
+  check:
+    if: always()
+    runs-on: ubuntu-latest
+    name: 🚦 Status Check
+    needs: [main]
+    steps:
+      - name: ℹ️ Test Matrix Result
+        run: |
+          echo result = ${{ needs.main.result }}
+      - name: ✅ Status Check - success
+        if: ${{ needs.main.result == 'success' }}
+        run: |
+          echo "All tests successfully completed!"
+          exit 0
+      - name: ❌ Status Check - failure
+        if: ${{ needs.main.result != 'success' }}
+        run: |
+          echo "Status Check failed!"
+          exit 1
